id: asdf://asdf-format.org/table/manifests/table-1.0.0
extension_uri: asdf://asdf-format.org/table/extensions/table-1.0.0
title: Table extension 1.0.0
description: |-
  A set of tags for serializing table into ASDF.
tags:
- tag_uri: tag:stsci.edu:asdf/core/column-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/core/column-1.0.0
  title: A column in a table.
  description: |-
    Each column contains a name and an array of data, and an optional description
    and unit.
- tag_uri: tag:stsci.edu:asdf/core/table-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/core/table-1.0.0
  title: A table.
  description: |-
    A table is represented as a list of columns, where each entry is a
    [column](ref:core/column-1.0.0)
    object, containing the data and some additional information.
    The data itself may be stored inline as text, or in binary in either
    row- or column-major order by use of the `strides` property on the
    individual column arrays.
    Each column in the table must have the same first (slowest moving)
    dimension.